/**
 * Auto-generated by scripts/translateUiLocales.js (see server repo).
 *
 * This file starts empty on purpose — the i18n engine deep-merges every
 * locale over the English base (see i18n/index.js), so an empty object
 * here just means every string falls back to English until the generator
 * script fills this in with real translations. Do not hand-edit; re-run
 * the script to regenerate, or edit individual keys here directly if you
 * want to override a specific machine translation (the script only
 * overwrites keys it translates, so hand overrides survive a re-run only
 * if you also pass --preserve-existing, see the script's usage comment).
 */
export default {};
